name: MSBuild

on: [push, pull_request]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: build\msw

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules # checkout backend repo as a submodule
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Cache wxWidgets
      id: cache-wx
      uses: actions/cache@v2
      with:
        path: wxWidgets-3.1.3
        key: ${{ runner.os }}-wx

    - name: Add MSBuild to PATH (Visual Studio 2019)
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,17.0)'
    
    - name: Build wxWidgets
      if: steps.cache-wx.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.zip -outfile wxWidgets-3.1.3.zip
        Expand-Archive wxWidgets-3.1.3.zip
        cd wxWidgets-3.1.3
        cd build/msw
        msbuild wx_vc16.sln --% /m /p:Configuration=${{env.BUILD_CONFIGURATION}};Platform=x64

    - name: Install wxWidgets
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: xcopy wxWidgets-3.1.3\* C:\wxwidgets-3.1.3\ /s /h /e
       
    
    - name: Build VocalTractLab
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /ignore:.vcxproj /t:VocalTractLab2